#ifndef ANIMATIONXMLPARSER_H
#define ANIMATIONXMLPARSER_H

#include "textanimation.h"
#include <QList>

namespace olive {

/// This class parses an XML string that is probably generated by
/// \a TextAnimationXmlFormatter.
/// A list of animation descriptors is extracted.
class TextAnimationXmlParser
{
public:
  TextAnimationXmlParser();

  /// \param xmlInput must contain opening and closing XML main tags.
  ///                 The format must comply with TextAnimationXmlFormatter
  static QList<TextAnimation::Descriptor> Parse( const QString & xmlInput);
};

}  // olive

#endif // ANIMATIONXMLPARSER_H
