#ifndef TIMELINETOOLS_H
#define TIMELINETOOLS_H

#define TIMELINE_TOOL_POINTER 0
#define TIMELINE_TOOL_EDIT 1
#define TIMELINE_TOOL_RAZOR 2
#define TIMELINE_TOOL_RIPPLE 3
#define TIMELINE_TOOL_ROLLING 4
#define TIMELINE_TOOL_SLIP 5
#define TIMELINE_TOOL_SLIDE 6
#define TIMELINE_TOOL_HAND 7
#define TIMELINE_TOOL_ZOOM 8
#define TIMELINE_TOOL_MENU 9

#endif // TIMELINETOOLS_H
