#ifndef TIMELINETOOLS_H
#define TIMELINETOOLS_H

enum TimelineTools {
	TIMELINE_TOOL_POINTER,
	TIMELINE_TOOL_EDIT,
	TIMELINE_TOOL_RAZOR,
	TIMELINE_TOOL_RIPPLE,
	TIMELINE_TOOL_ROLLING,
	TIMELINE_TOOL_SLIP,
	TIMELINE_TOOL_HAND,
	TIMELINE_TOOL_ZOOM
};

#endif // TIMELINETOOLS_H
